# Generated by Django 4.2.2 on 2024-12-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
