# Generated by Django 4.2.2 on 2025-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
