# Generated by Django 4.2.2 on 2024-11-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(default='Not Specified', help_text='Town or city name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for delivery (optional)', max_length=500, null=True),
        ),
    ]
