# Generated by Django 4.2.2 on 2025-01-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
