# Generated by Django 4.2.2 on 2024-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('cash', 'Cash on Delivery')], max_length=10, null=True),
        ),
    ]
