# Generated by Django 4.2.2 on 2024-12-20 10:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_supportticket_order_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_review',
            unique_together={('user', 'order')},
        ),
        migrations.RemoveField(
            model_name='order_review',
            name='product',
        ),
    ]
