# Generated by Django 4.2.2 on 2024-12-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
