# Generated by Django 4.2.2 on 2025-01-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartorder_mpesa_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payheropayment',
            name='payhero_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
