# Generated by Django 4.2.2 on 2024-12-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_is_new_arrival_product_is_special_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
    ]
