# Generated by Django 4.2.2 on 2024-12-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
