# Generated by Django 4.2.2 on 2024-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_supportticket_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_review',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
