# Generated by Django 4.2.2 on 2024-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_review_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
