# Generated by Django 4.2.2 on 2024-12-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productreview_is_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
