# Generated by Django 4.2.2 on 2024-12-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
