# Generated by Django 4.2.2 on 2025-01-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_options_payheropayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payheropayment',
            name='order',
        ),
        migrations.AddField(
            model_name='payheropayment',
            name='cart_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='payheropayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled')], default='PENDING', max_length=20),
        ),
    ]
