# Generated by Django 4.2.2 on 2025-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_payheropayment_order_payheropayment_cart_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payheropayment',
            name='cart_data',
            field=models.JSONField(),
        ),
    ]
