# Generated by Django 4.2.2 on 2025-01-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_payheropayment_cart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payheropayment',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shippingaddress'),
        ),
    ]
