# Generated by Django 4.2.2 on 2025-01-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_payheropayment_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payheropayment',
            name='order',
            field=models.ForeignKey(default='dict', on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
        ),
    ]
