# Generated by Django 4.2.2 on 2025-01-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_payheropayment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payheropayment',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
        ),
    ]
