# Generated by Django 4.2.2 on 2025-01-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_payheropayment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payheropayment',
            name='order',
        ),
    ]
